server:
  port: 8080
  tomcat.threads.max: 400
  servlet:
    context-path: /persistence

# DATABASE
spring.jpa:
  database: MYSQL
  hibernate.ddl-auto: create-only
  show-sql: true
  properties:
    hibernate:
      globally_quoted_identifiers: true
      globally_quoted_identifiers_skip_column_definitions: true

# Specify the path of the OpenAPI documentation
spring-doc:
  api-docs.path: /open-api/api-docs
  swagger-ui.path: /open-api/swagger-ui.html
  swagger-ui.enabled: true

spring.datasource:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:30080/fitness_challenge
  username: fitness-challenge
  password: Zml0bmVzcy1jaGFsbGVuZ2UjMTIzIQ==
