apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: fitness-challenge
  name: fitness-challenge-mysql
spec:
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: fitness-challenge-mysql
  template:
    metadata:
      labels:
        app: fitness-challenge-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: persistence-fitness-challenge-config
            - secretRef:
                name: persistence-secret
          volumeMounts:
            - mountPath: /etc/config
              name: config
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 125m
              memory: 256Mi
      imagePullSecrets:
        - name: docker-registry-pass
      volumes:
        - name: config
          configMap:
            name: persistence-fitness-challenge-config