apiVersion: v1
kind: Service
metadata:
  namespace: fitness-challenge
  name: persistence-mysql-np
  labels:
    app: fitness-challenge-mysql-np
spec:
  type: NodePort
  selector:
    app: fitness-challenge-mysql
  ports:
    -  protocol: TCP
       port: 3306
       targetPort: 3306
       nodePort: 30080