apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume
  namespace: fitness-challenge
  labels:
    type: local
spec:
  storageClassName: storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"